# **Project 1- Ad Sale Prediction from existiong customer- Logistic Regression**

**Importing Libraries**

In [1]:
import pandas as pd # useful for loading the dataset
import numpy as np #to perform array


**Choose Dataset file from Local Directory**

In [2]:
data = pd.read_csv(R"C:\Users\csc\OneDrive\Desktop\Python Program\Project 1- Sale prediction from an existing customer using LOGISTIC REGRESSION\ad_dataseto.csv")

**Load Dataset using pandas library**

In [3]:
dataset = pd.read_csv(R'C:\Users\csc\OneDrive\Desktop\Python Program\Project 1- Sale prediction from an existing customer using LOGISTIC REGRESSION\ad_dataseto.csv')
print(dataset)

      Age   Salary  Status
0      25  1252600       1
1      38  1256200       0
2      28  1260000       1
3      44  1264000       0
4      18  1268200       1
...   ...      ...     ...
1471   48    64000       0
1472   47    64300       0
1473   55    64600       0
1474   22    64900       0
1475   49    65200       0

[1476 rows x 3 columns]


**Summarize Dataset**

In [4]:
print(dataset.shape) # no. of rows and columns
print(dataset.head(5)) #top values of data

(1476, 3)
   Age   Salary  Status
0   25  1252600       1
1   38  1256200       0
2   28  1260000       1
3   44  1264000       0
4   18  1268200       1


**Segrate Dataset into X(Input/Independent Variable) and Y(Output/Dependent Variable)**

In [5]:
X = dataset.iloc[:, :-1].values
X

array([[     25, 1252600],
       [     38, 1256200],
       [     28, 1260000],
       ...,
       [     55,   64600],
       [     22,   64900],
       [     49,   65200]], dtype=int64)

In [6]:
Y = dataset.iloc[:,-1].values
Y

array([1, 0, 1, ..., 0, 0, 0], dtype=int64)

**Splitting Dataset into Train and Test**

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.25, random_state=0)

***Feature Scaling***
we scale our data to make all the features contribute equally to the result
Fit_Transform- fit method is calculating the mean and variance of each of the features present in our data.

**Transform** - Transform method is transforming alll the features using the respective mean and variance,
We want our test data to be completely new and a surprise set for our model


In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train)


[[ 0.83787255  1.73577786]
 [ 1.71829487 -1.21104156]
 [-0.99634061  1.48202494]
 ...
 [-0.26265535  0.70329007]
 [-1.28981472  1.42959665]
 [-0.33602387  0.51035396]]


**Training/Algorithm**

In [9]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression() #loading the algorithm
model.fit(X_train, Y_train)  #train

LogisticRegression()

**Prediction for all Test Data**

In [10]:
Y_pred = model.predict(X_test)
#print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y_test.reshape(len(Y_test),1)),1))

**Evaluating Model- CONFUSION MATRIX**

In [11]:
#from sklearn.matrics import confusion_matrix, accuracy_score
from sklearn.metrics import accuracy_score
# cm = confusion_matrix(Y_test, Y_pred)

#print(" Confusion Matrix: ")
#print(cm)

print(" Accuracy of the Model: {0}% ".format(accuracy_score(Y_test, Y_pred)*100))

 Accuracy of the Model: 65.04065040650406% 


**Predicting, wheather new customer with Age and Salary will Buy or Not**

In [12]:
age = int(input(" Enter New Customer's Age: "))
salary = int(input(" Enter New Customer's Salary: "))
newCust = [[age,salary]]
result = model.predict(sc.transform(newCust))
print(result)
if result == 1:
  print("Customer will Buy")
else:
  print("Customer won't Buy")  

[0]
Customer won't Buy
